name: Run CI
on:
  push:
    branches: [ main, REL* ]
  pull_request:
    branches: [ main, REL* ]

jobs:
  ci:
    strategy:
      matrix:
        include:
          - mw: 'REL1_45'
            php: 8.2
            experimental: false
          - mw: 'REL1_46'
            php: 8.3
            experimental: false
          - mw: 'master'
            php: 8.3
            experimental: true
          - mw: 'master'
            php: 8.4
            experimental: true

    uses: weirdgloop/ci-workflows/.github/workflows/extension-ci.yml@main
    with:
      extension-name: 'Speedscope'
      mw-branch: ${{ matrix.mw }}
      php-version: ${{ matrix.php }}
      php-extensions: 'zlib, excimer'
      experimental: ${{ matrix.experimental }}
